---
- name: Cloner le repo et exécuter les scripts
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour et mise à niveau des paquets
      become: yes
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
    - name: Installer Git
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Installer Java
      apt:
        name:
          - openjdk-11-jdk
          - ca-certificates-java

    - name: Cloner le repo GitHub
      git:
        repo: "https://github.com/Salmamakina/script-installation-bigdata"
        dest: "/tmp/repo_installation"
        version: main
        force: yes

    - name: Donner les permissions d'exécution au script hadoop-spark
      file:
        path: "/tmp/repo_installation/install-hadoop-spark.sh"
        mode: "0755"

    - name: Donner les permissions d'exécution au script drill-zookeeper
      file:
        path: "/tmp/repo_installation/install-drill-zookeeper.sh"
        mode: "0755"

    - name: Donner les permissions d'exécution au script Adding env var
      file:
        path: "/tmp/repo_installation/Adding-env-var.sh"
        mode: "0755"

    - name: Obtenir le nombre de cœurs CPU
      shell: "lscpu | grep '^CPU(s):' | awk '{print $2}'"
      register: cpu_output
      changed_when: false

    - name: Extraire le nombre de cœurs CPU
      set_fact:
        max_cpu: "{{ cpu_output.stdout }}"

    - name: Obtenir la RAM totale
      shell: "free -m | grep '^Mem:' | awk '{print $2}'"
      register: ram_output
      changed_when: false

    - name: Extraire la RAM totale en MB
      set_fact:
        max_ram: "{{ ram_output.stdout }}"

    - name: Tâches spécifiques au master
      when: inventory_hostname == "master-vm-test"
      block:
        - name: Donner les permissions d'exécution au script install-docker
          file:
            path: "/tmp/repo_installation/install-docker.sh"
            mode: "0755"
        
        - name: Installation Docker et Docker-compose
          shell: "bash /tmp/repo_installation/install-docker.sh"
          become: yes
          become_user: root
          environment:
            PATH: "{{ ansible_env.PATH }}"  # S'assurer que le chemin est correctement défini pour l'utilisateur
        
    - name: Extraire le rôle du host (master ou worker)
      set_fact:
        role: "{{ inventory_hostname.split('-')[0] }}"

    - name: Installer Hadoop et Spark
      shell: "bash /tmp/repo_installation/install-hadoop-spark.sh {{ hostvars['master-vm-test'].ansible_host }} {{ role }} {{ max_cpu }} {{ max_ram }}"
      become: yes
      become_user: root

    - name: Ajouter les variables d'environnement
      shell: "bash /tmp/repo_installation/Adding-env-var.sh {{ role }} /root"
      become: yes

    - name: Installer Drill et Zookeeper
      shell: "bash /tmp/repo_installation/install-drill-zookeeper.sh {{ hostvars['master-vm-test'].ansible_host }} {{ hostvars['worker-vm-test'].ansible_host }} {{ role }}"
      become: yes
      become_user: root

