global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
          - '10.1.0.2:9100'  # Adresse interne de la VM master
          - '10.1.0.3:9100'  # Adresse interne de la VM worker


